title: Climate Adaptation and Fly Biology Laboratory
description: The lab studies the biochemical and neurochemical mechanisms through which climate stress affects human‑relevant neural function and mosquito vector fitness
theme: minima
markdown: kramdown

header_pages:
  - research.md
  - people.md
  - publications.md
  - contact.md
